config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pictures#index', as: :root

  resources :users, except: :index

  resources :pictures
  post 'pictures/:id/black_and_white', to: 'pictures#black_and_white', as: :bw
  post 'pictures/:id/edge', to: 'pictures#edge', as: :edge
  post 'pictures/:id/sepia', to: 'pictures#sepia', as: :sepia
  post 'pictures/:id/charcoal', to: 'pictures#charcoal', as: :charcoal
  post 'pictures/:id/sketch', to: 'pictures#sketch', as: :sketch
  post 'pictures/:id/vignette', to: 'pictures#vignette', as: :vignette
  post 'pictures/:id/polaroid', to: 'pictures#polaroid', as: :polaroid
  post 'pictures/:id/make_bigger', to: 'pictures#make_bigger', as: :make_bigger
  post 'pictures/:id/make_smaller', to: 'pictures#make_smaller', as: :make_smaller
  post 'pictures/:id/make_thumbnail', to: 'pictures#make_thumbnail', as: :make_thumbnail
  post 'pictures/:id/flip_vertical', to: 'pictures#flip_vertical', as: :flip_vertical
  post 'pictures/:id/flip_horizontal', to: 'pictures#flip_horizontal', as: :flip_horizontal




  resources :categories
  resources :tags

  # Picture Categories
  post '/picture-categories', to: 'picture_categories#create', as: :create_picture_category
  delete 'pictures/:picture_id/picture-categories/:id', to: 'picture_categories#destroy', as: :destroy_picture_category

  # Picture Tags
  delete '/pictures/:picture_id/picture-tags/:id', to: 'picture_tags#destroy', as: :destroy_picture_tag

  # Following Users
  post '/user-leaders/:leader_id', to: 'user_leaders#create', as: :create_user_leader

  # Favorites
  post '/users/:user_id/favorites/:picture_id', to: 'favorites#create', as: :create_favorite
  delete '/users/:user_id/favorites/:id', to: 'favorites#destroy', as: :destroy_favorite

  # Session
  get '/login', to: 'sessions#new', as: :login
  post '/sessions', to: 'sessions#create', as: :create_session
  delete '/sessions/:id', to: 'sessions#destroy', as: :destroy_session

end

app/models/picture.rb
require 'RMagick'
require 'face_detect'
require 'face_detect/adapter/google'
require 'rest_client'
require 'base64'
require 'json'
GOOGLE_CREDENTIALS_JSON= "/Users/admin/flatiron/labs/rails/mark-and-scott-rails-project-web-031317/keys/pixr-23da4be727f5.json"
include Magick

class Picture < ApplicationRecord
  has_attached_file :image, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :picture_categories
  has_many :categories, -> { distinct }, through: :picture_categories
  has_many :picture_tags
  has_many :tags, -> { distinct }, through: :picture_tags
  belongs_to :user
  has_many :favorites, foreign_key: "favorite_picture_id", dependent: :destroy
  has_many :favorited_by, -> { distinct }, through: :favorites

  validates :user_id, presence: true
  validates :image, presence: true

  def non_category
    Category.all - categories
  end

  def category_list=(string)
    categories_array = string.split(",")
    categories_array = categories_array.map do |category|
      Category.find_or_create_by( name: category.strip )
    end
    self.categories = categories_array
  end

  #modifier methods
  def greyscale
    #grabs path of image on our server
    path = self.image.path
    #create a new "Image List" object from the image at the path
    image = ImageList.new(path)
    #uses the quantize method to set the number of colors used in the image to 2
    image = image.quantize(nc=2)
    #this saves the file in the location it was before
    new_path = path.gsub(/\/original\/(.+\.)(...|....)/, '/original/grey-scale-\1\2')
    image.write(new_path)
    #use this for testing, need to have X11 runnning for it to work
    #image.display
  end

  def destructive_greyscale
    path = self.image.path
    image = ImageList.new(path)
    image = image.quantize(nc=2)
    image.write(path)
  end

  def make_bigger
    path = self.image.path
    image = ImageList.new(path)
    image = image.magnify
    image.write(path)
  end

  def make_smaller
    path = self.image.path
    image = ImageList.new(path)
    image = image.minify
    image.write(path)
  end

  def make_thumbnail
    path = self.image.path
    image = ImageList.new(path)
    image = image.thumbnail(image.columns*0.09, image.rows*0.09)
    image.write(path)
  end

  def flip_vertical
    path = self.image.path
    image = ImageList.new(path)
    image = image.flip
    image.write(path)
  end

  def flip_horizontal
    path = self.image.path
    image = ImageList.new(path)
    image = image.flop
    image.write(path)
  end

  def edge
    path = self.image.path
    image = ImageList.new(path)
    image = image.edge
    image.write(path)
  end

  def sepia
    path = self.image.path
    image = ImageList.new(path)
    image = image.sepiatone
    image.write(path)
  end

  def charcoal
    path = self.image.path
    image = ImageList.new(path)
    image = image.charcoal
    image.write(path)
  end

  def sketch
    path = self.image.path
    image = ImageList.new(path)
    image = image.sketch
    image.write(path)
  end

  def vignette
    path = self.image.path
    image = ImageList.new(path)
    image = image.vignette
    image.write(path)
  end

  def polaroid
    path = self.image.path
    image = ImageList.new(path)
    image = image.vignette
    image.write(path)
  end

  def grey_scale_improved
    path = self.image.path
    image = ImageList.new(path)
    new_pixels = image.get_pixels(0, 0, image.columns, image.rows)
    for pixel in new_pixels
      average = (pixel.red + pixel.green + pixel.blue) / 3
      pixel.red = average

      pixel.green = average
      pixel.blue = average
    end
    image.store_pixels(0,0, image.columns,image.rows, new_pixels)
    image.write(path)

    #image.import_pixels(0,0,image.columns,image.rows,new_pixels, "RGB").display
  end


  #image evaluators
  def red?
    if color_percentages[:red_percentage] > 0.4
      true
    else
      false
    end
  end

  def blue?
    if color_percentages[:blue_percentage] > 0.4
      true
    else
      false
    end
  end

  def green?
    if color_percentages[:green_percentage] > 0.4
      true
    else
      false
    end
  end


  def color_percentages
    path = self.image.path
    image = ImageList.new(path)
    values = {}
    values[:red] = 0
    values[:blue] = 0
    values[:green] = 0
    new_pixels = image.get_pixels(0, 0, image.columns, image.rows)
    for pixel in new_pixels
      values[:green] += pixel.green
      values[:blue] += pixel.blue
      values[:red] += pixel.red
    end
    total_count = values[:red] + values[:blue] + values[:green]

    #return
    {
      :red_percentage => values[:red].to_f/total_count,
      :green_percentage => values[:green].to_f/total_count,
      :blue_percentage => values[:blue].to_f/total_count
    }

    #deprecated: old return for max percentage, now handling in separate method
    # values.max_by{|k,v| v}[0]

  end

  def monochrome?
    path = self.image.path
    #create a new "Image List" object from the image at the path
    image = ImageList.new(path)
    #uses the quantize method to set the number of colors used in the image to 2
    image.monochrome?
    #this will return true if the image is monochrome, then we can add that as a category
  end

  def gray?
    path = self.image.path
    #create a new "Image List" object from the image at the path
    image = ImageList.new(path)
    #uses the quantize method to set the number of colors used in the image to 2
    image.gray?
    #this will return true if the image is monochrome, then we can add that as a category
  end

  def tagorize
    #implicit self, self.tags and tags are the same thing here
    if green?
      tags << Tag.find_or_create_by(name: "Green")
    end
    if red?
      tags << Tag.find_or_create_by(name: "Red")
    end
    if blue?
      tags << Tag.find_or_create_by(name: "Blue")
    end
    if gray?
      tags << Tag.find_or_create_by(name: "Gray")
    end
    if face?
      tags << Tag.find_or_create_by(name: "Face")
    end
  end

  def tagorize_improved

    image_url = Adapter::CloudinaryAdapter.generate_url_for(image)
    response = Adapter::RestClientAdapter.generate_response(image_url)
    data = Adapter::RestClientAdapter.generate_tags(response)
    data[0..5].each do |element|
      tags << Tag.find_or_create_by(name: element["tag"])
    end
    if face? #add face tag if there's a face in the image
      tags << Tag.find_or_create_by(name: "Face")
    end
  end


  def face?
    if face_detect
      #if this returns an object, it means a face was detected
      true
    else
      false
    end
  end

  def face_detect
    input = File.new(image.path)
    detector = FaceDetect.new(
      file: input,
      adapter: FaceDetect::Adapter::Google
    )
    results = detector.run
    #results
    face = results.first
    face
  end

  #analyzation methods

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  #changed this to skip before action because I'm adding a ton of new routes and don't want to have to type them out
  before_action :set_picture, except: [:new, :create, :index]
  before_action :set_categories, only: [:new, :edit]
  before_action :restrict_to_users, except: [:index, :show]

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new( picture_params )

    @picture.user = current_user
    if @picture.save
      @picture.tagorize_improved
      redirect_to picture_path( @picture )
    else
      redirect_to :new, notice: @picture.errors.full_messages
    end
  end

  def index
    @pictures = Picture.all
  end

  def update
    if @picture.update( picture_params )
      @picture.tagorize
      redirect_to picture_path( @picture )
    else
      redirect_to :edit, notice: @picture.errors.full_messages
    end
  end

  def destroy
    @picture.destroy
    redirect_to user_path( current_user ), notice: ["Successfully deleted #{@picture.name}"]
  end

  def black_and_white
    @picture = Picture.find(params[:id])
    @picture.grey_scale_improved
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def edge
    @picture.edge
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def sepia
    @picture.sepia
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end
  def charcoal
    @picture.charcoal
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def sketch
    @picture.sketch
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def vignette
    @picture.vignette
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end
  def polaroid
    @picture.polaroid
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end
  def make_bigger
    @picture.make_bigger
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end
  def make_smaller
    @picture.make_smaller
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def make_thumbnail
    @picture.make_thumbnail
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def flip_vertical
    @picture.flip_vertical
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end

  def flip_horizontal
    @picture.flip_horizontal
    @picture.save
    redirect_to "/pictures/#{params[:id]}"
  end



  private

  def set_picture
    @picture = Picture.find( params[:id] )
  end

  def set_categories
    @categories = Category.all
  end

  def picture_params
    params_hash = params.require( :picture ).permit( :image, :name )
    params_hash[:category_ids] = params.require( :picture ).require( :category_ids )
    params_hash
  end
end

app/views/pictures/edit.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  if ($(':selected')) {
    $('label[for="picture_category_ids"]').addClass('active');
  }
  $('.collapsible').collapsible();
});
</script>
<% if flash[:notice].present? %>
  <% flash[:notice].each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="row">
  <div class="col s12">
    <h5>Preview:</h5>
    <%= image_tag @picture.image.url %>
    <ul class="collapsible" data-collapsible="expandable">
      <li>
        <div class="collapsible-header">Picture Effects</div>
        <div class="collapsible-body">
          <ul class="collection">
            <li><%= link_to "B&W", bw_path(@picture), method: 'post' %></li>
            <li><%= link_to "Edge", edge_path(@picture), method: 'post' %></li>
            <li><%= link_to "Sepia", sepia_path(@picture), method: 'post' %></li>
            <li><%= link_to "Charcoal", charcoal_path(@picture), method: 'post' %></li>
            <li><%= link_to "Sketch", sketch_path(@picture), method: 'post' %></li>
            <li><%= link_to "Vignette", vignette_path(@picture), method: 'post' %></li>
            <li><%= link_to "Polaroid", polaroid_path(@picture), method: 'post' %></li>
          </ul>
        </div>
      </li>
      <li>
        <div class="collapsible-header">Formatting</div>
        <div class="collapsible-body">
          <ul class="collection">
            <li><%= link_to "Double Size", make_bigger_path(@picture), method: 'post' %></li>
            <li><%= link_to "Half Size", make_smaller_path(@picture), method: 'post' %></li>
            <li><%= link_to "Thumbnail", make_thumbnail_path(@picture), method: 'post' %></li>
            <li><%= link_to "Flip Vertically", flip_vertical_path(@picture), method: 'post' %></li>
            <li><%= link_to "Flip Horizontally", flip_horizontal_path(@picture), method: 'post' %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s6">
    <%= form_for @picture do |f| %>
    <div class="input-field">
      <%= f.label :name, class: 'active' %>
      <%= f.text_field :name %>
    </div>
    <div class="input-field file-field">
      <div class="btn">
        <%= f.label :image, class: 'hidden' %>
        <span>Image</span>
        <%= f.file_field :image %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div class="input-field">
      <%= f.label :category_ids, "Categories" %>
      <select name="picture[category_ids][]" multiple>
        <option value="" disabled selected>Select at least one category</option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>" <%= 'selected' if @picture.category_ids.include?( category.id ) %>><%= category.name %></option>
        <% end %>
      </select>
    </div>
    <%= f.submit class: "btn waves-effect waves-light" %>
    <% end %>
  </div>
</div>

app/views/pictures/index.html.erb
<h2>All Images:</h2>
<% if flash[:notice].present? %>
  <div class="row">
    <div class="col s12 m5">
      <div class="card-panel red">
        <% flash[:notice].each do |message| %>
          <p class="white-text">
            <%= message %>
          </p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="row grid">
  <% @pictures.sort_by { |picture| picture.favorited_by.count }.reverse.each do |picture| %>
    <% if !logged_in? || picture.user_id != current_user.id %>
      <%= render partial: "picture", locals: { picture: picture } %>
    <% end %>
  <% end %>
</div>

app/views/pictures/new.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  function readURL(input) {
      if (input.files && input.files[0]) {
          var reader = new FileReader();

          reader.onload = function (e) {
              $('#preview-image').attr('src', e.target.result);
          }

          reader.readAsDataURL(input.files[0]);
      }
  }

  $("#picture_image").change(function(){
      readURL(this);
      $('#preview').removeClass('hidden');
  });

  if ($(':selected')) {
    $('label[for="picture_category_ids"]').addClass('active');
  }

});
</script>
<% if flash[:notice].present? %>
  <% flash[:notice].each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="row">
  <div class="col s12 m6">
    <%= form_for @picture do |f| %>
    <div class="input-field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="input-field file-field">
      <div class="btn">
        <%= f.label :image, class: 'hidden' %>
        <span>Image</span>
        <%= f.file_field :image %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="Select a picture to upload">
      </div>
    </div>
    <div class="input-field">
      <%= f.label :category_ids, "Categories" %>
      <select name="picture[category_ids][]" multiple>
        <option value="" disabled selected>Choose at least one Category</option>
        <% @categories.each do |category| %>
          <option value="<%= category.id %>"><%= category.name %></option>
        <% end %>
      </select>
    </div>
    <%= f.submit class: "btn waves-effect waves-light" %>
    <% end %>
  </div>
  <div class="col s12 m6">
    <div id="preview" class="card hidden">
      <div class="card-image">
        <img id="preview-image" src="#" alt="Image Preview">
      </div>
    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="row picture-title valign-wrapper">
  <div class="col s4 m6">
    <h3><%= @picture.name %></h3>
  </div>
  <div class="col s8 m6 valign-wrapper">
    <h4>Uploaded by <%= link_to "#{@picture.user.username}", @picture.user %></h4>
    <% if logged_in? && !user_authorized? && !following_picture_owner? %>
      <%= link_to "Follow #{@picture.user.username}", "/user-leaders/#{@picture.user.id}", class: "btn waves-effect waves-light", method: "post" %>
    <% end %>
  </div>
</div>
<div class="card">
  <div class="card-image">
    <%= image_tag @picture.image.url %>
  </div>
  <div class="card-content">
    <h5>Categories:</h5>
    <% @picture.picture_categories.each do |pic_category| %>
      <div class="chip">
        <%= link_to pic_category.category.name, pic_category.category %>

        <% if logged_in? && user_authorized? %>
          <%= link_to "<i class='close material-icons'></i>".html_safe, "/pictures/#{@picture.id}/picture-categories/#{pic_category.id}", method: "delete"%>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<h5>Tags</h5>
  <% @picture.picture_tags.each do |pic_tag| %>
    <div class='chip'>
      <%= link_to pic_tag.tag.name, pic_tag.tag %>
      <% if logged_in? && user_authorized? %>
        <%= link_to "<i class='close material-icons'></i>".html_safe, "/pictures/#{@picture.id}/picture-tags/#{pic_tag.id}", method: "delete" %>
      <% end %>
    </div>
  <% end %>
<% if logged_in? && user_authorized? %>
  <p><%= link_to "Edit Image", edit_picture_path( @picture ), class: "btn waves-effect waves-light" %>
  <%= link_to "Delete Image", "/pictures/#{@picture.id}", class: "btn waves-effect waves-light", method: "delete" %></p>
<% end %>