config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'pictures#index', as: :root

  resources :users, except: :index

  resources :pictures
  post 'pictures/:id/black_and_white', to: 'pictures#black_and_white', as: :bw
  post 'pictures/:id/edge', to: 'pictures#edge', as: :edge
  post 'pictures/:id/sepia', to: 'pictures#sepia', as: :sepia
  post 'pictures/:id/charcoal', to: 'pictures#charcoal', as: :charcoal
  post 'pictures/:id/sketch', to: 'pictures#sketch', as: :sketch
  post 'pictures/:id/vignette', to: 'pictures#vignette', as: :vignette
  post 'pictures/:id/polaroid', to: 'pictures#polaroid', as: :polaroid
  post 'pictures/:id/make_bigger', to: 'pictures#make_bigger', as: :make_bigger
  post 'pictures/:id/make_smaller', to: 'pictures#make_smaller', as: :make_smaller
  post 'pictures/:id/make_thumbnail', to: 'pictures#make_thumbnail', as: :make_thumbnail
  post 'pictures/:id/flip_vertical', to: 'pictures#flip_vertical', as: :flip_vertical
  post 'pictures/:id/flip_horizontal', to: 'pictures#flip_horizontal', as: :flip_horizontal




  resources :categories
  resources :tags

  # Picture Categories
  post '/picture-categories', to: 'picture_categories#create', as: :create_picture_category
  delete 'pictures/:picture_id/picture-categories/:id', to: 'picture_categories#destroy', as: :destroy_picture_category

  # Picture Tags
  delete '/pictures/:picture_id/picture-tags/:id', to: 'picture_tags#destroy', as: :destroy_picture_tag

  # Following Users
  post '/user-leaders/:leader_id', to: 'user_leaders#create', as: :create_user_leader

  # Favorites
  post '/users/:user_id/favorites/:picture_id', to: 'favorites#create', as: :create_favorite
  delete '/users/:user_id/favorites/:id', to: 'favorites#destroy', as: :destroy_favorite

  # Session
  get '/login', to: 'sessions#new', as: :login
  post '/sessions', to: 'sessions#create', as: :create_session
  delete '/sessions/:id', to: 'sessions#destroy', as: :destroy_session

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize_user, :restrict_to_users, :user_authorized?, :following_picture_owner?

  private
  def logged_in?
    session[:user_id].present?
  end

  def restrict_to_users
    unless logged_in?
      redirect_to root_path
    end
  end

  def user_authorized?
    session[:user_id] == @picture.user_id
  end

  def authorize_user
    unless params[:id].to_i == session[:user_id]
      redirect_to root_path
    end
  end

  def current_user
    if logged_in?
      @current_user ||= User.find( session[:user_id] )
    end
  end

  def following_picture_owner?
    @following = current_user.leaders.include?( @picture.user )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_favorites_slider.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  $('.slider').slider();
});
</script>
<div class="slider">
    <ul class="slides">
      <% current_user.favorites.each do |favorite| %>
        <li>
            <%= link_to "<img src='#{favorite.favorite_picture.image.url}'>".html_safe, favorite.favorite_picture %>
          <div class="caption center-align">
            <h3><%= favorite.favorite_picture.name %></h3>
            <%= link_to "<i class='material-icons red-text'>favorite_border</i>".html_safe, "/users/#{favorite.favorited_by.id}/favorites/#{favorite.id}", class: "btn-floating waves-effect waves-light white tooltipped", 'data-position': "bottom", 'data-delay': "50", 'data-tooltip': "Remove Favorite", method: "delete" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/application/_leaders_slider.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  $('.slider').slider();
});
</script>
<div class="slider">
  <ul class="slides">
    <% leader.pictures.each do |picture| %>
    <li>
      <%= link_to "<img src='#{picture.image.url}'>".html_safe, picture %>
      <div class="caption center-align">
        <h3><%= picture.name %></h3>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/application/_nav_bar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <div class="row">
        <div class="col s2 m1">
          <%= link_to 'Pixr', root_path, id:"logo" %>
        </div>
        <% if logged_in? %>
            <ul class="right">
              <li class="left-bar">
                <%= link_to "<i class='material-icons pre-word'>face</i><span class='post-pre-word'>View your pics</span>".html_safe, current_user, class: "valign-wrapper" %>
              </li>
              <li class="left-bar">
                <%= link_to "<i class='material-icons pre-word'>add_a_photo</i><span class='post-pre-word'>Add a Picture</span>".html_safe, new_picture_path, class: "valign-wrapper" %>
              </li>
              <li class="left-bar">
                <%= link_to "Logout", "/sessions/#{current_user.id}", method: 'delete' %>
              </li>
            </ul>
        <% else %>
          <div class="col s10 m8 l6 right">
            <div class="row">
              <div class="col s2 left-bar">
                <%= link_to "Sign Up", new_user_path %>
              </div>
              <%= form_tag '/sessions', class: "col s10 left-bar" do %>
                <div class="row">
                  <div class="input-field inline col s4">
                    <i class="material-icons prefix">account_circle</i>
                    <%= label_tag :username, "Username:" %>
                    <%= text_field_tag :username %>
                  </div>
                  <div class="input-field inline col s4">
                    <i class="material-icons prefix">fingerprint</i>
                    <%= label_tag :password, "Password:" %>
                    <%= password_field_tag :password %>
                  </div>
                  <div class="col s4">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                      Login
                    </button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/application/_picture.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: '.grid-sizer',
    percentPosition: true
  });
});
</script>
  <div class="col m6 l4 grid-sizer grid-item">
    <div class="card hoverable">
      <div class="card-image">
        <%= link_to "<img src='#{picture.image.url}'><span class='card-title'>#{picture.name}</span>".html_safe, picture %>
        <% if logged_in? && current_user != picture.user %>
          <% if current_user.favorite_pictures.include?( picture ) %>
            <%= link_to "<i class='material-icons red-text'>favorite_border</i>".html_safe, "/users/#{current_user.id}/favorites/#{Favorite.find_by( favorited_by: current_user, favorite_picture: picture ).id}", class: "btn-floating halfway-fab waves-effect waves-light white tooltipped", 'data-position': "bottom", 'data-delay': "50", 'data-tooltip': "Remove Favorite", method: "delete" %>
          <% else %>
            <%= link_to "<i class='material-icons'>favorite</i>".html_safe, "/users/#{current_user.id}/favorites/#{picture.id}", class: "btn-floating halfway-fab waves-effect waves-light red tooltipped", 'data-position': "bottom", 'data-delay': "50", 'data-tooltip': "Add Favorite", method: "post" %>
          <% end %>
        <% else %>
          <p class="btn-floating halfway-fab red center-align">
            +<%= picture.favorited_by.count %>
          </p>
        <% end %>
      </div>
      <div class="card-content">
        <% picture.categories.each do |category| %>
        <div class="chip">
          <%= link_to category.name, category %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/application/_slider.html.erb
<script>
$( document ).on('turbolinks:load', function() {
  $('.slider').slider();
});
</script>
<div class="slider">
    <ul class="slides">
      <% current_user.favorites.each do |favorite| %>
        <li>
            <%= link_to "<img src='#{favorite.favorite_picture.image.url}'>".html_safe, favorite.favorite_picture %>
          <div class="caption center-align">
            <h3><%= favorite.favorite_picture.name %></h3>
            <%= link_to "<i class='material-icons red-text'>favorite_border</i>".html_safe, "/users/#{favorite.favorited_by.id}/favorites/#{favorite.id}", class: "btn-floating waves-effect waves-light white tooltipped", 'data-position': "bottom", 'data-delay': "50", 'data-tooltip': "Remove Favorite", method: "delete" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>